### ISSUE TITLE
chore: custom breakpoints in tailwind config with other repo standards

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Guidlify/guidlify.com#1]
1. tailwind.config.js

> It is better if we add custom breakpoints.

```javascript
      screens: {
        xs: '200px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        // 2xl: '1536px',
      },
```      
      
2. Since this is going to be public at some point, so it will be better if we can add basic standards like
   - Security.md
   - CODE_OF_CONDUCT.md

3. I will make separate issues for completing different sections of the website as per figma design.

**Comment by vinzvinci** [comment]
Looks good. Also, do you have access in our [Projects Board](https://github.com/orgs/WebXGuild/projects/1)? it is currently private.

**Comment by Anmol-Baranwal** [comment]
> Looks good. Also, do you have access in our [Projects Board](https://github.com/orgs/WebXGuild/projects/1)? it is currently private.

Yes, I have the access.
